### ISSUE TITLE
You little thief

### ISSUE THREAD

**Issue by cybrann** [JadeCore/JadeCore_5.x.x#1]
So you stole our work and you didn't even give credits, you little piece of shit

**Comment by a7244869** [comment]
I want work with your but don't know  how to join

**Comment by cybrann** [comment]
Go to our source and open issue where you tell that you want to join

**Comment by Bodeguero** [comment]
@cybrann I'm not stealing anyone I asked you to team to become more organized that did not accept the invitation?

**Comment by cooler-SAI** [comment]
@Bodeguero  close all here please, or we will go private

**Comment by Bodeguero** [comment]
@cooler-SAI yes man! I invite you to the team as an administrator to be well organized if you want more I close everything! You want me to quit?

**Comment by cybrann** [comment]
I never said to quit, but wouldn't it be more fun if we all worked on same source, instead of opening thousand more?

**Comment by Bodeguero** [comment]
@cybrann  Yes why I invite you all to the team as Administrators - I'm even thinking of buying the domain to give all the necessary support!

**Comment by cybrann** [comment]
Ok, but 1 more thing, fork our source from https://github.com/cooler-SAI/JadeCore548-patched not upload new so that all commits can be seen.

**Comment by cooler-SAI** [comment]
guys, ( I mean my team ) you wanna join this source?

**Comment by cooler-SAI** [comment]
summoning @alexkulya

**Comment by cybrann** [comment]
@cooler-SAI I would like to if you all are, but only if you remain boss :)

**Comment by cooler-SAI** [comment]
I can't be 100% boss if it's don't mine repo, I don't like this 5.x.x style ( we have current 5.4.7 ( 18019) version) , Joslynn will come back soon and can lost us, so, my opinion - we stay https://github.com/cooler-SAI/JadeCore548-patched repo

**Comment by cybrann** [comment]
That's what I would love. If you can just update name to something like JadeCore only and name branch 5.4.x until we change to 5.4.8 18414 build.

**Comment by cooler-SAI** [comment]
@cybrann , done

**Comment by cybrann** [comment]
I'll update also our readme.md to match trinity core style too so we can attract more people to join

**Comment by Bodeguero** [comment]
@cooler-SAI  and @cybrann I can then close this project?

**Comment by cybrann** [comment]
@Bodeguero Yep and cooler shall invite you to our and then we will all be happy :)

**Comment by Bodeguero** [comment]
@cybrann and @cooler-SAI Let's open a website too? To do all support? I can sponsoring the website!

**Comment by Mysterium** [comment]
What for a website? Only a forum?
And sry cooler for no commits, it's a bit stressful because my baby..

**Comment by cybrann** [comment]
@Bodeguero Ok, also I'll take your readme.md file and edit it a bit, ok ?

**Comment by Bodeguero** [comment]
@cybrann Ok

**Comment by Bodeguero** [comment]
@cybrann and @cooler-SAI  What repository will work? Here or there really?

**Comment by cybrann** [comment]
https://github.com/cooler-SAI/JadeCore @Bodeguero I updated readme and it looks really nice now.

**Comment by Bodeguero** [comment]
@cybrann @cooler-SAI You can put me on the team to work together?

**Comment by cooler-SAI** [comment]
@Bodeguero , welcome https://github.com/cooler-SAI/JadeCore/invitations

**Comment by Bodeguero** [comment]
@cooler-SAI Can I delete an organization?

**Comment by cooler-SAI** [comment]
@Mysterium , it's ok!! help when you wanna and can )))

**Comment by cooler-SAI** [comment]
@Bodeguero we can use your organisation if you can copy here all our commits - I TRYED BUT FAILED ((((

**Comment by Bodeguero** [comment]
@cooler-SAI A moment I will try to do this - make a repository that will correct all your commits is what you want?

**Comment by Mysterium** [comment]
@cooler-SAI all right :)
should i set up a forum for this project on my server? i don't use the server, so i can set up a hp or forum on it
